const QUESTIONS = {

  general: [
    "Qu'est-ce qui occupe le plus ton esprit en ce moment ?",
    "Quelle émotion domines-tu aujourd'hui sans t'en rendre compte ?",
    "Si tu pouvais changer une chose dans ta journée d'hier, ce serait quoi ?",
    "Qu'est-ce que tu évites de penser depuis quelques jours ?",
    "Quelle décision tu repousses encore ?",
    "Qu'est-ce que tu ferais si tu n'avais pas peur du regard des autres ?",
    "À quel moment de la semaine tu te sens vraiment toi-même ?",
    "Qu'est-ce qui te donne encore de l'énergie quand tout va mal ?",
    "Quelle habitude tu sais que tu devrais arrêter mais tu continues quand même ?",
    "Qui dans ta vie te tire vers le haut ? Tu lui as dit merci ?",
    "Qu'est-ce que tu n'as jamais osé dire à voix haute ?",
    "Si dans 10 ans tu regardes aujourd'hui, qu'est-ce que tu voudrais avoir fait différemment ?",
    "Qu'est-ce qui te manque en ce moment, concrètement ?",
    "Quelle croyance sur toi-même tu commences à questionner ?",
    "Qu'est-ce que tu attends que quelqu'un d'autre fasse à ta place ?",
    "Qu'est-ce qui te pèse mais que tu appelles encore 'pas grave' ?",
    "À quel moment as-tu été fier de toi récemment, même pour quelque chose de petit ?",
    "Qu'est-ce que tu fais pour les autres que tu ne fais jamais pour toi ?",
    "Si ton corps pouvait parler, qu'est-ce qu'il te dirait aujourd'hui ?",
    "Qu'est-ce que tu appelles repos mais qui t'épuise en fait ?",
    "Quelle version de toi tu veux être dans 6 mois ?",
    "Qu'est-ce qui t'a surpris en toi cette semaine ?",
    "Quel mensonge confortable tu te racontes en ce moment ?",
    "Qu'est-ce que tu ne supportes plus mais que tu tolères encore ?",
    "Quand as-tu dit oui alors que tu voulais dire non ?",
    "Qu'est-ce qui te met dans un état de flow sans effort ?",
    "Quelle partie de ta vie tu négliges depuis trop longtemps ?",
    "Qu'est-ce que tu fais par habitude et non par envie réelle ?",
    "Quel besoin tu as du mal à exprimer aux autres ?",
    "Qu'est-ce qui te rendrait vraiment fier de toi d'ici ce soir ?",
    "Quelle peur revient régulièrement dans tes pensées ?",
    "À qui tu en veux encore sans te l'avouer ?",
    "Qu'est-ce que tu attendais de cette année qui n'est pas venu ?",
    "Quel compliment t'a le plus touché récemment et pourquoi ?",
    "Qu'est-ce que tu refuses de voir en toi ?",
    "Quelle limite tu n'as toujours pas posée ?",
    "Qu'est-ce qui te fatigue dans ton quotidien actuel ?",
    "Si tu pouvais parler à la version de toi d'il y a 5 ans, tu lui dirais quoi ?",
    "Qu'est-ce que tu fais uniquement pour plaire aux autres ?",
    "Quel moment de ta journée est vraiment pour toi ?",
    "Qu'est-ce que tu repousseras encore demain si tu ne le fais pas aujourd'hui ?",
    "Quelle relation dans ta vie te coûte plus qu'elle ne t'apporte ?",
    "Qu'est-ce qui te définissait avant que tu ne te définit plus aujourd'hui ?",
    "Quelle pensée récurrente tu aimerais arrêter d'avoir ?",
    "Qu'est-ce que tu ferais si tu savais que tu ne peux pas échouer ?",
    "Qu'est-ce que les gens proches de toi ne savent pas sur toi ?",
    "À quel besoin profond tu ne réponds pas en ce moment ?",
    "Quelle colère tu n'as jamais vraiment exprimée ?",
    "Qu'est-ce qui t'empêche de dormir certaines nuits ?",
    "Qu'est-ce que tu appelles ta faiblesse mais qui pourrait être ta force ?",
    "Quel rêve tu as abandonné sans vraiment décider de l'abandonner ?",
    "Qu'est-ce que tu fais quand tu te sens dépassé ?",
    "Quelle conversation tu évites depuis trop longtemps ?",
    "Qu'est-ce qui te donne l'impression d'être vivant ?",
    "Comment tu te traites quand tu fais une erreur ?",
    "Qu'est-ce que tu n'acceptes pas encore dans ta situation actuelle ?",
    "Quelle version de toi tu joues devant certaines personnes ?",
    "Qu'est-ce que tu cherches dans les distractions que tu utilises en ce moment ?",
    "Quel aspect de ta vie ressemble le moins à ce que tu voulais ?",
    "Qu'est-ce qui te fait te sentir en sécurité ?",
    "Quelle blessure ancienne refait surface en ce moment ?",
    "Qu'est-ce que tu veux vraiment, sans filtre ?",
    "Comment tu réagis face à l'incertitude, honnêtement ?",
    "Qu'est-ce qui te rend jaloux et qu'est-ce que ça dit sur tes désirs ?",
    "Quelle valeur tu dis avoir mais tu ne vis pas vraiment ?",
    "Qu'est-ce que tu n'as jamais pardonné à quelqu'un ?",
    "À quel moment tu te sens le plus vulnérable ?",
    "Qu'est-ce que tu fais pour fuir plutôt qu'affronter ?",
    "Quelle image de toi tu voudrais que les autres aient ?",
    "Qu'est-ce que tu n'as jamais pris le temps de célébrer ?",
    "Quel sacrifice tu fais en ce moment sans que personne le sache ?",
    "Qu'est-ce qui te manque dans tes relations actuelles ?",
    "Quelle routine te fait du bien mais que tu abandonnes trop vite ?",
    "Qu'est-ce que tu n'oses pas demander ?",
    "Quelle partie de ton passé tu portes encore inutilement ?",
    "Qu'est-ce que tu apprendrais si tu n'avais pas peur d'être nul au départ ?",
    "À quel moment tu te sens le plus aligné avec qui tu veux être ?",
    "Qu'est-ce que tu sacrifies pour un confort qui ne te satisfait plus ?",
    "Quelle promesse tu t'es faite et que tu n'as pas tenue ?",
    "Qu'est-ce que tu assumes mal mais que tu assumes quand même ?",
    "Quel aspect de toi tu n'aimes pas mais que tu n'essaies pas de changer ?",
    "Qu'est-ce qui te donne le sentiment d'être utile ?",
    "Quelle peur t'a déjà rendu plus fort une fois surmontée ?",
    "Qu'est-ce que ton entourage voit en toi que tu ne vois pas ?",
    "Qu'est-ce qui t'a changé profondément ces dernières années ?",
    "Quel besoin tu mets en dernier alors qu'il devrait être en premier ?",
    "Qu'est-ce que tu refuses de demander de l'aide pour ?",
    "Comment tu sais quand tu vas vraiment bien ?",
    "Quel moment de ta vie tu reviens souvent, et pourquoi ?",
    "Qu'est-ce qui t'empêche d'être la version que tu veux être ?",
    "Quelle décision passée tu regrettes encore, et qu'est-ce qu'elle t'a appris ?",
    "Qu'est-ce que tu fais par devoir mais jamais par plaisir ?",
    "Quelle qualité chez toi tu sous-estimes constamment ?",
    "Qu'est-ce qui a changé dans ta façon de voir le monde cette année ?",
    "Quel aspect de ta vie actuelle te surprendrait si tu l'avais prédit il y a 5 ans ?",
    "Qu'est-ce que tu n'acceptes pas encore de toi-même ?"
  ],

  amour: [
    "Qu'est-ce que tu cherches vraiment dans une relation amoureuse ?",
    "Comment tu te comportes quand tu aimes quelqu'un et que tu as peur de le perdre ?",
    "Qu'est-ce que tu n'as jamais osé dire à ton partenaire ou à quelqu'un qui t'attire ?",
    "À quel moment tu te sens le plus aimé(e) ?",
    "Qu'est-ce que tu acceptes dans une relation que tu ne devrais pas ?",
    "Comment tu réagis quand l'autre a besoin de distance ?",
    "Quelle blessure d'une relation passée influence encore tes comportements aujourd'hui ?",
    "Qu'est-ce que tu attends de l'autre sans jamais le formuler clairement ?",
    "Est-ce que tu te sens libre d'être toi-même dans ta relation ou avec la personne que tu aimes ?",
    "Quelle peur t'empêche de t'engager pleinement ?",
    "Qu'est-ce que tu fais pour te protéger émotionnellement dans une relation ?",
    "Comment tu sais que tu aimes vraiment quelqu'un ?",
    "Qu'est-ce que tu sacrifies dans une relation sans jamais le dire ?",
    "Quelle est ta façon de montrer de l'amour, et est-ce que c'est compris ?",
    "Qu'est-ce qui te blesse le plus dans une relation sans que tu l'exprimes ?",
    "Comment tu gères la jalousie — en toi ou chez l'autre ?",
    "Qu'est-ce que tu appelles de l'amour mais qui ressemble à de la dépendance ?",
    "Quelle limite tu n'as jamais posée dans une relation et tu le regrettes ?",
    "Est-ce que tu choisis des partenaires qui te ressemblent ou qui te complètent ?",
    "Qu'est-ce que tu n'as jamais pardonné dans une relation passée ?",
    "Comment tu te comportes après une dispute — tu fuis ou tu restes ?",
    "Qu'est-ce que tu n'accepterais jamais dans une relation selon toi, mais que tu as accepté ?",
    "Quelle conversation tu évites avec ton partenaire ou la personne que tu aimes ?",
    "Qu'est-ce que tu fais quand tu doutes d'une relation ?",
    "Comment ton rapport à l'amour a changé depuis ta première relation ?",
    "Qu'est-ce que tu cherches dans une relation que tu n'as jamais vraiment eu ?",
    "Est-ce que tu te sens capable d'aimer sans conditions ?",
    "Quel besoin émotionnel ton partenaire ne comble pas, et en as-tu parlé ?",
    "Qu'est-ce qui te donne confiance dans une relation ?",
    "Comment tu réagis quand tu te sens incompris(e) par quelqu'un que tu aimes ?",
    "Quelle habitude dans ta relation actuelle ou passée te pèse ?",
    "Qu'est-ce que la solitude t'a appris sur ce que tu veux dans une relation ?",
    "Quelle est la chose la plus courageuse que tu aies faite par amour ?",
    "Comment tu distingues l'amour de l'attachement anxieux ?",
    "Qu'est-ce que tu n'as jamais demandé à un partenaire mais dont tu avais besoin ?",
    "Quel rôle tu joues dans les conflits de tes relations amoureuses ?",
    "Qu'est-ce que tu appellerais une relation saine pour toi ?",
    "Comment tu réagis quand quelqu'un te montre de l'amour d'une façon que tu n'attends pas ?",
    "Qu'est-ce qui t'attire chez quelqu'un, et est-ce que ça t'a déjà causé du mal ?",
    "Est-ce que tu aimes vraiment l'autre ou l'idée que tu as de lui/elle ?",
    "Qu'est-ce que tu fais quand tu sens que l'autre s'éloigne ?",
    "Quelle peur liée à l'abandon influence tes relations ?",
    "Est-ce que tu sais recevoir de l'amour sans te sentir redevable ?",
    "Qu'est-ce qui te manque dans ta vie amoureuse actuelle ?",
    "Comment tu traites l'autre quand tu vas mal émotionnellement ?",
    "Quelle leçon une rupture t'a apprise sur toi-même ?",
    "Est-ce que tu te bats pour une relation ou tu attends que l'autre le fasse ?",
    "Qu'est-ce que tu ne veux plus vivre dans une prochaine relation ?",
    "Comment tu exprimes tes besoins affectifs sans te sentir faible ?",
    "Quelle image idéalisée de l'amour tu as du mal à abandonner ?",
    "Qu'est-ce que tu fais pour entretenir une relation, concrètement ?",
    "Comment tu sais quand une relation est terminée ?",
    "Quelle partie de toi tu caches à ceux que tu aimes ?",
    "Est-ce que tu as déjà aimé quelqu'un sans être prêt(e) à l'accueillir dans ta vie ?",
    "Quelle différence tu fais entre aimer et avoir besoin de quelqu'un ?",
    "Qu'est-ce que tu attends d'une relation que tu pourrais te donner toi-même ?",
    "Comment tu gères l'intimité émotionnelle — est-ce que ça te fait peur ?",
    "Quelle erreur tu répètes dans tes relations amoureuses ?",
    "Qu'est-ce que le respect signifie pour toi dans une relation ?",
    "Est-ce que tu t'es déjà perdu(e) dans une relation au détriment de toi-même ?",
    "Comment tu te comportes quand tu n'es pas sûr(e) des sentiments de l'autre ?",
    "Qu'est-ce qui te donne envie de construire quelque chose avec quelqu'un ?",
    "Quelle limite floue dans une relation te rend anxieux(se) ?",
    "Est-ce que tu aimes mieux quand tu te sens en sécurité ou quand c'est intense ?",
    "Qu'est-ce que tu as appris sur toi dans ta dernière relation ?",
    "Comment tu réagis face à la vulnérabilité de l'autre ?",
    "Quelle place tu accordes à l'amour dans tes priorités de vie ?",
    "Qu'est-ce que tu n'assumes pas encore dans ce que tu veux affectivement ?",
    "Est-ce que tu sais ce que tu apportes dans une relation ?",
    "Quelle attente non formulée a déjà causé une rupture ou un conflit ?",
    "Comment tu vis la routine dans une relation — comme une sécurité ou un piège ?",
    "Qu'est-ce qui te fait encore croire en l'amour malgré les déceptions ?",
    "Quel schéma relationnel tu reproduis depuis l'enfance sans le choisir vraiment ?",
    "Qu'est-ce que tu ferais différemment si tu pouvais recommencer une relation passée ?",
    "Comment tu sais que tu es prêt(e) pour une relation sérieuse ?",
    "Qu'est-ce que la confiance représente pour toi dans un couple ?",
    "Est-ce que tu t'aimes assez pour exiger d'être bien traité(e) ?",
    "Quelle blessure d'enfance se manifeste dans tes relations amoureuses ?",
    "Qu'est-ce que tu cherches dans les yeux de quelqu'un qui t'attire ?",
    "Comment tu vis la fin d'une relation — tu t'effondres, tu te fermes, tu avances ?",
    "Quelle conversation honnête tu dois avoir avec toi-même sur ta vie amoureuse ?",
    "Est-ce que tu as déjà choisi quelqu'un par peur de la solitude ?",
    "Qu'est-ce que tu ne négocierais jamais dans une relation ?",
    "Comment tu cultives le désir dans une relation longue durée ?",
    "Quelle part de responsabilité tu prends dans les difficultés de tes relations ?",
    "Est-ce que tu sais demander pardon sincèrement ?",
    "Qu'est-ce qui te donne le sentiment d'être vraiment vu(e) par quelqu'un ?",
    "Comment tu réagis quand une relation ne ressemble pas à ce que tu espérais ?",
    "Quelle promesse tu t'es faite sur ta vie amoureuse et tu ne tiens pas ?",
    "Est-ce que tu t'autorises à vouloir plus dans ta vie amoureuse ?",
    "Qu'est-ce que l'amour t'a coûté que tu n'étais pas prêt(e) à payer ?",
    "Comment tu fais la différence entre une mauvaise période et une mauvaise relation ?",
    "Quelle version de toi ressort dans une relation amoureuse dont tu n'es pas fier(e) ?",
    "Qu'est-ce que tu n'as jamais eu dans une relation et dont tu as pourtant besoin ?",
    "Est-ce que tu sais encore ce que tu ressens pour la personne qui partage ta vie ?",
    "Qu'est-ce que tu t'interdis de ressentir dans le domaine amoureux ?"
  ],

  bienetre: [
    "Qu'est-ce qui draine ton énergie mentale en ce moment sans raison apparente ?",
    "Quand as-tu pris du temps pour toi pour la dernière fois, vraiment ?",
    "Qu'est-ce que tu appelles te reposer mais qui ne te régénère pas vraiment ?",
    "Quelle pensée revient en boucle et t'empêche d'avancer ?",
    "Comment tu te parles quand tu fais une erreur — tu serais ami avec quelqu'un qui te parle comme ça ?",
    "Qu'est-ce qui t'aide vraiment à décompresser ?",
    "Quelle émotion tu as du mal à accueillir en toi ?",
    "Est-ce que tu te sens en paix avec où tu en es dans ta vie ?",
    "Qu'est-ce que tu fais pour éviter de ressentir quelque chose d'inconfortable ?",
    "Quelle habitude te sabote sans que tu l'admettes clairement ?",
    "Qu'est-ce qui te donne un sentiment de légèreté ?",
    "À quel moment de la journée tu te sens le plus en paix ?",
    "Qu'est-ce que tu portes seul(e) que tu pourrais partager ?",
    "Comment tu réagis quand les choses ne se passent pas comme prévu ?",
    "Qu'est-ce que le perfectionnisme t'a coûté ?",
    "Quelle pensée sur toi-même tu répètes depuis des années et d'où vient-elle ?",
    "Est-ce que tu te permets de ne rien faire sans culpabiliser ?",
    "Qu'est-ce qui t'aide à te sentir ancré(e) quand tu es perdu(e) ?",
    "Comment tu distingues la fatigue physique de la fatigue émotionnelle ?",
    "Quelle comparaison avec les autres te fait le plus de mal ?",
    "Qu'est-ce que tu fais par peur du jugement plutôt que par envie ?",
    "Quel besoin fondamental tu ignores régulièrement ?",
    "Comment tu t'es senti(e) la dernière fois que tu as demandé de l'aide ?",
    "Qu'est-ce que tu fais pour nourrir ta créativité ou ta curiosité ?",
    "Quelle anxiété tu as appris à gérer, et comment ?",
    "Est-ce que tu vis dans le passé, le futur ou le présent en ce moment ?",
    "Qu'est-ce qui te donne le sentiment d'être à ta place ?",
    "Comment tu gères les périodes où tu ne te reconnais plus ?",
    "Qu'est-ce que tu fais quand tu te sens overwhelmed ?",
    "Quel espace dans ta vie te manque pour être toi-même ?",
    "Qu'est-ce qui t'aide à accepter ce que tu ne peux pas contrôler ?",
    "Quelle relation dans ta vie impacte le plus ton état mental ?",
    "Est-ce que tu te sens coupable de prendre soin de toi en premier ?",
    "Qu'est-ce que tu ferais différemment si tu te traitais comme ton meilleur ami ?",
    "Quelle croyance limite ton épanouissement sans que tu la questionnes ?",
    "Comment tu sais que tu as besoin de te reposer avant d'être épuisé(e) ?",
    "Qu'est-ce qui te connecte à quelque chose de plus grand que toi ?",
    "Quelle peur contrôle encore beaucoup de tes décisions ?",
    "Est-ce que tu accordes autant de bienveillance aux autres qu'à toi-même ?",
    "Qu'est-ce que la gratitude change concrètement dans tes journées ?",
    "Comment tu crées de la joie dans ton quotidien quand rien n'est particulier ?",
    "Qu'est-ce que tu as arrêté de faire qui te manque vraiment ?",
    "Quelle émotion tu ne t'autorises pas à exprimer ?",
    "Est-ce que tu sais ce dont tu as besoin pour être heureux(se) ?",
    "Qu'est-ce qui a changé dans ton rapport à toi-même ces 2 dernières années ?",
    "Comment tu accueilles tes propres contradictions ?",
    "Quelle partie de toi tu rejettes que tu pourrais apprendre à intégrer ?",
    "Qu'est-ce que ton corps essaie de te dire en ce moment ?",
    "Comment tu réagis face à la critique — tu l'intègres ou tu te défends ?",
    "Quelle conversation avec toi-même tu remets depuis trop longtemps ?",
    "Qu'est-ce qui te donne de l'espoir quand tu vas mal ?",
    "Quel moment de ta journée tu pourrais protéger juste pour toi ?",
    "Qu'est-ce que tu fais de tes émotions difficiles — tu les fuis, tu les traverses ou tu les ignores ?",
    "Comment tu reconstruis ta confiance après un échec ?",
    "Qu'est-ce qui t'empêche de te sentir libre dans ta propre vie ?",
    "Quelle chose simple tu as longtemps négligée et qui change tout quand tu la fais ?",
    "Est-ce que tu sais recevoir un compliment sans le minimiser ?",
    "Qu'est-ce que tu t'interdis de ressentir parce que tu penses que tu ne le mérites pas ?",
    "Comment tu vis les transitions — les fins et les nouveaux départs ?",
    "Quelle part de ta vie tu laisses au hasard alors que tu pourrais agir ?",
    "Qu'est-ce qui t'aide à sortir de la spirale négative quand tu y es ?",
    "Comment tu t'organises pour protéger ton énergie mentale ?",
    "Quelle habitude de pensée te nuit le plus en ce moment ?",
    "Est-ce que tu te permets d'être imparfait(e) sans t'effondrer ?",
    "Qu'est-ce que la paix intérieure signifie pour toi concrètement ?",
    "Quel besoin tu exprimes de façon indirecte sans jamais le nommer vraiment ?",
    "Qu'est-ce qui te rend fier(e) de toi indépendamment du regard des autres ?",
    "Comment tu identifies ce qui est sous ton contrôle et ce qui ne l'est pas ?",
    "Qu'est-ce que tu aurais besoin d'entendre de toi-même en ce moment ?",
    "Quelle routine matinale ou du soir t'aide vraiment à te sentir bien ?",
    "Est-ce que tu t'accordes le droit d'avoir des mauvaises journées sans te juger ?",
    "Qu'est-ce qui t'aide à maintenir un sentiment de continuité quand tout change ?",
    "Comment tu te réconcilies avec des parties de ton passé que tu n'aimes pas ?",
    "Qu'est-ce que tu fais encore par obligation que tu pourrais lâcher ?",
    "Quelle limite tu dois poser pour protéger ta santé mentale ?",
    "Est-ce que tu nourris ton esprit autant que tu nourris ton corps ?",
    "Qu'est-ce qui te manque pour te sentir vraiment épanoui(e) ?",
    "Comment tu gères l'ennui — il te dérange ou tu l'utilises ?",
    "Quelle émotion tu ressens souvent mais tu as du mal à nommer ?",
    "Qu'est-ce qui te reconnecte à toi-même quand tu t'es perdu(e) de vue ?",
    "Est-ce que tu vis ta vie selon tes propres critères ou ceux des autres ?",
    "Quel aspect de ta santé mentale tu as longtemps ignoré et qui revient aujourd'hui ?",
    "Qu'est-ce que tu ferais si tu savais que personne ne te juge ?",
    "Comment tu cultives un sentiment de sécurité intérieure ?",
    "Quelle petite chose quotidienne améliore vraiment ton humeur ?",
    "Est-ce que tu te donnes le droit de changer d'avis sur ce que tu veux ?",
    "Qu'est-ce que tu n'as jamais dit à voix haute sur ton état intérieur ?",
    "Comment tu sais quand tu as besoin d'aide professionnelle ?",
    "Quelle émotion tu juges chez les autres et qui est en fait la tienne ?",
    "Qu'est-ce qui te donne la force de continuer dans les moments difficiles ?",
    "Est-ce que tu crois en ta capacité à changer ce qui ne te convient plus ?",
    "Qu'est-ce que tu aurais besoin de te pardonner pour avancer ?",
    "Comment tu distingues le lâcher-prise de la résignation ?",
    "Quelle version de toi tu veux protéger à tout prix ?",
    "Qu'est-ce que tu peux faire aujourd'hui pour te traiter avec plus de douceur ?",
    "Comment tu mesures ton bien-être — à quoi tu sais que tu vas vraiment bien ?"
  ]

};
